name: build
on:
  workflow_dispatch:
    inputs:
      version:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: gradle/actions/setup-gradle@v6
    - run: ./gradlew publish
      env:
        INPUTS_VERSION: ${{ inputs.version }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
